ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS payout_status TEXT NOT NULL DEFAULT 'NOT_ELIGIBLE',
  ADD COLUMN IF NOT EXISTS platform_fee INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS owner_amount INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS paid_out_at TEXT;

ALTER TABLE orders
  DROP CONSTRAINT IF EXISTS orders_payout_status_check;

ALTER TABLE orders
  ADD CONSTRAINT orders_payout_status_check
  CHECK (payout_status IN ('NOT_ELIGIBLE', 'ELIGIBLE', 'PAID_OUT', 'REFUND_REQUIRED', 'REFUNDED'));
